version: '3.8'

services:
  gin:
    image: zhangyiming748/translate-service:latest
    ports:
      - "6380:6380"
    container_name: gin
    volumes:
      - ./log:/log
      - ./data:/data
    environment:
      - keyword=Alohomora # 这里设置的关键词代表每次网络请求要带的参数 参数一致才会提供翻译服务 防止服务被滥用
