version: '3.8'

services:
  gin:
    image: zhangyiming748/translate-service:latest
    ports:
      - "6380:80"
    container_name: gin
    volumes:
      - ./log:/log
      - ./data:/data
    environment:
      - abracadabra=abracadabra
